package org.swiftsuspenders.reflection;

import org.swiftsuspenders.typedescriptions.TypeDescription;

class MacroReflector implements Reflector {
	// this is initialized by the code generated by TypeDescriptionMacro
	static var factories:haxe.DynamicAccess<TypeDescription->Void>;

	public function new() {}

	public inline function getClass(value:Dynamic):Class<Dynamic> {
		return Type.getClass(value);
	}

	public function describeInjections(type:Class<Dynamic>):TypeDescription {
		var description = new TypeDescription();
		var factory = factories[Type.getClassName(type)];
		if (factory != null) {
			// TODO: maybe we should throw here?
			factory(description);
		}
		return description;
	}
}
